controller_list:
  - name: /panda_arm_1/position_joint_trajectory_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - panda_arm_1_joint1
      - panda_arm_1_joint2
      - panda_arm_1_joint3
      - panda_arm_1_joint4
      - panda_arm_1_joint5
      - panda_arm_1_joint6
      - panda_arm_1_joint7
