controller_list:
  - name: /panda_arm_2/position_joint_trajectory_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - panda_arm_2_joint1
      - panda_arm_2_joint2
      - panda_arm_2_joint3
      - panda_arm_2_joint4
      - panda_arm_2_joint5
      - panda_arm_2_joint6
      - panda_arm_2_joint7
