<?xml version="1.0" encoding='utf-8'?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="panda_softhand">

  <!-- ARGS -->
  <xacro:arg name="arm_id"
    default="panda" />
  <xacro:arg name="robot_ns" default="panda" />

  <!-- MODELS -->
  <xacro:include
    filename="$(find qb_hand_description)/urdf/qbhand.utils.xacro" />

  <!-- Include Panda ARM -->
  <xacro:include
    filename="$(find panda_softhand_description)/robot/arm/darko_franka_robot.xacro" />
  <xacro:include
    filename="$(find panda_softhand_description)/robot/utils/decorations.xacro" />
  <xacro:include
    filename="$(find panda_softhand_description)/robot/utils/properties.xacro" />

  <!-- Flags to load properly the end-effectors -->
  <xacro:arg name="prefix" default="panda" />

  <!-- Franka Gripper -->
  <xacro:arg name="hand" default="false" />

  <!-- WORLD -->
  <link
    name="world" />
  <link name="box_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}" />
      </geometry>
      <material name="Red" />
    </visual>

    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}" />
      </geometry>
    </collision>
  </link>

  <joint
    name="world_to_box_joint" type="fixed">
    <origin xyz="0.0 0.0 ${base_height / 2.0}" rpy="0.0 0.0 0.0" />
    <parent link="world" />
    <child link="box_link" />
  </joint>

  <!-- PANDA ARM -->
  <xacro:darko_franka_robot
    joint_limits="${xacro.load_yaml('$(find franka_description)/robots/panda/joint_limits.yaml')}"
    hand="$(arg hand)"
    prefix="$(arg prefix)"
    parent="box_link">
    <origin xyz="${arm_position_x} ${arm_position_y} ${base_height / 2.0}"
      rpy="${arm_orientation_r} ${arm_orientation_p} ${arm_orientation_y}" />
  </xacro:darko_franka_robot>

  <!-- RIGHT SOFTHAND2 -->
  <xacro:arg
    name="namespace" default="qbhand1m" />
  <xacro:build_hand_from_yaml_with_90_deg_flange
    configuration="qbhand_right"
    namespace="$(arg namespace)" parent="panda_link8" parent_link_suffix="">
    <origin xyz="0.045 0 0.035" rpy="1.57 0 1.57" />
  </xacro:build_hand_from_yaml_with_90_deg_flange>

  <!-- EXTRA ENDEFFECTOR -->
  <joint
    name="right_hand_ee_joint" type="fixed">
    <origin xyz="0.102 -0.003 0.037" rpy="0 0 0" />
    <parent link="panda_link8" />
    <child link="right_hand_ee_link" />
  </joint>

  <link name="right_hand_ee_link">
  </link>

</robot>