 controller_list:
  - name: /panda_dual/panda_arm_1_position_joint_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - panda_arm_1_joint1
      - panda_arm_1_joint2
      - panda_arm_1_joint3
      - panda_arm_1_joint4
      - panda_arm_1_joint5
      - panda_arm_1_joint6
      - panda_arm_1_joint7
      - panda_arm_2_joint1
      - panda_arm_2_joint2
      - panda_arm_2_joint3
      - panda_arm_2_joint4
      - panda_arm_2_joint5
      - panda_arm_2_joint6
      - panda_arm_2_joint7
  