# Parameters for task sequencer
# Remember that there might be other important constants that can only be changed from the src code.

grasp_params:
  # Name of the robot
  robot_name: panda_arm
  # Name of the robot joints (without the number of the joints)
  robot_joints_name: panda_joint
  # Position controller
  pos_controller: position_joint_trajectory_controller
  # Impedance controller
  imp_controller: cartesian_impedance_controller_softbots_stiff_matrix
  # Name of the topic where the object pose is published
  object_topic_name: /grasp/chosen_object

  # The joint configuration for home
  #home_joints: [0.00996, -0.7360, -0.0044, -2.0562, -0.0173, 1.4542, 0.03390] 
  home_joints: [0.01029, -1.0670, -0.0415, -2.5372, 0.0068, 1.5150, 0.0140]
  #1) PRESA VERTICALE SFERA
  # Transform from object frame to grasp pose frame (xyzrpy) (DEFAULT) 
  #grasp_transform: [-0.137, 0.000, 0.228, 2.880, 0.713, 0.072] #presa verticale sfera

  # Transform from grasp pose frame to pre-grasp pose frame (xyzrpy) CENTRALE 
  #pre_grasp_transform: [-0.137, -0.0, 0.514, 2.880, 0.713, 0.072] #laterale, se voglio centale y=0.0

  #2) PRESA DI LATO SFERA
  #grasp_transform: [-0.208, -0.063, 0.129, -1.625, 0.129, 0.010]
  #pre_grasp_transform: [-0.208, -0.063, 0.485, -1.625, 0.129, 0.010] 


#1) PRESA VERTICALE CILINDRO
  # Transform from object frame to grasp pose frame (xyzrpy) (DEFAULT) 
  grasp_transform: [-0.150, 0.002, 0.185, 3.108, 0.360, -0.162] #presa verticale sfera

  # Transform from grasp pose frame to pre-grasp pose frame (xyzrpy) CENTRALE 
  pre_grasp_transform: [-0.160, 0.002, 0.538, 3.108, 0.360, -0.162] #laterale, se voglio centale y=0.0

