# Parameters for task sequencer
# Remember that there might be other important constants that can only be changed from the src code.

task_sequencer:
  # Name of the robot
  robot_name: panda_arm
  # Name of the robot joints (without the number of the joints)
  robot_joints_name: panda_joint
  # Position controller
  pos_controller: position_joint_trajectory_controller
  # Impedance controller
  imp_controller: cartesian_impedance_controller_softbots_stiff_matrix
  # Name of the topic where the object pose is published (grasping)
  object_topic_name: /grasping/chosen_object

  # The joint configuration for home
  home_joints: [-0.035, -0.109, -0.048, -1.888, 0.075, 1.797, -0.110] 

  ################## PREGRASP AND GRASP TRANSFORM ##############################
  # Transform from object frame to grasp pose frame (xyzrpy) (DEFAULT)
  # grasp_transform: [-0.04, -0.04, 0.145, -3.1415, 0.0, 0.0] (default)
  grasp_transform: [0.308, -0.396, 0.560, 1.411, 0.087, -0.406]
  # Transform from grasp pose frame to pre-grasp pose frame (xyzrpy)
  pre_grasp_transform: [0.0, 0.0, -0.1, 0.0, 0.0, 0.0]

  ################# PREVACUUM JOINTS CONFIGURATION AND VACUUM TRANSFORM ########
  # # Transform from object frame to vacuum pose frame (xyzrpy) (DEFAULT)
  # vacuum_transform: [0.605, -0.202, 0.380, 1.600, -0.042, -0.207]
  # # Transform from grasp pose frame to pre-grasp pose frame (xyzrpy)
  # pre_vacuum_transform: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  
  pre_throwing_joints: [0.020080210122173526, -0.31461428480813536, -0.24156380251834267, -2.30914939719754, -1.7265883330714096, 1.8092104921274714, 0.36461395125477397]
  
  pre_vacuum_transform: [0.0, 0.1, 0.0, 0.0, 0.0, 0.0]
  vacuum_transform: [0.579, -0.189, 0.186, 1.573, 0.120, 0.059]

  ############### JOINT THROWING CONFIGURATION ################################
  
  throwing_joints: [-0.14460508277907705, 0.06115021342613056, -0.3366816540349994, -1.8161098990362778, 1.3733559124204846, 1.228444780661, 0.23411068879538813]
  
  # The personalized place joints maps for different prevacuuming joint configurations

  pre_vacuum_joints_map:
    "object2" : [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    "object3" : [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

  throwing_joints_map:
    "object2" : [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    "object3" : [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

  # The joint configuration for place
  place_joints: [-0.068, 0.152, 0.193, -2.352, 0.0405, 2.519, 0.117]
  # The joint configuration for handover
  handover_joints: [-0.101, 0.161, 0.159, -1.651, 2.023, 2.419, -0.006]
  # The threshold on tau_ext for handover hand opening
  handover_thresh: 1.0

  # The personalized grasp pose maps for different objects
  poses_map:
    "red" : [-0.085, 0.005, 0.008, -3.039, -0.185, -0.166]
    "green" : [-0.085, 0.005, 0.008, -3.039, -0.185, -0.166]
    "blue" : [-0.085, 0.005, 0.008, -3.039, -0.185, -0.166]
    "black" : [-0.085, 0.005, 0.008, -3.039, -0.185, -0.166]
    "white" : [-0.085, 0.005, 0.008, -3.039, -0.185, -0.166]
    "other" : [-0.085, 0.005, 0.008, -3.039, -0.185, -0.166]

  # The personalized place joints maps for different objects
  place_joints_map:
    "red" : [0.092, 0.929, 0.129, -1.153, -0.115, 2.010, -0.417]
    "green" : [-0.140, 0.738, 0.0913, -1.577, -0.103, 2.267, 0.060]
    "blue" : [-0.352, 0.882, 0.038, -1.331, -0.0290, 2.149, 0.126]
    "black" : [-0.352, 0.882, 0.038, -1.331, -0.0290, 2.149, 0.126]
    "white" : [-0.352, 0.882, 0.038, -1.331, -0.0290, 2.149, 0.126]
    "other" : [-0.352, 0.882, 0.038, -1.331, -0.0290, 2.149, 0.126]