# Parameters for task sequencer
# Remember that there might be other important constants that can only be changed from the src code.

task_sequencer:
  # Name of the robot
  robot_name: panda_arm
  # Name of the robot joints (without the number of the joints)
  robot_joints_name: panda_joint
  # Position controller
  pos_controller: position_joint_trajectory_controller
  # Impedance controller
  imp_controller: cartesian_impedance_controller_softbots_stiff_matrix
  # Name of the topic where the object pose is published
  object_topic_name: /irim_demo/chosen_object


  ########################### HANDTOOL SERVICES #########################
  #-------------------------- Going to home configuration -------------#
  home_joints: [-0.035, -0.109, -0.048, -1.888, 0.075, 1.797, -0.110] 
  
  #------------------------ Grasping handtools-----------------------#
  # Transform from object frame to grasp pose frame (xyzrpy) (DEFAULT)
  # grasp_transform: [-0.04, -0.04, 0.145, -3.1415, 0.0, 0.0] (default)
  grasp_transform: [0.302, -0.412, 0.576, 1.566, 0.195, -0.218]
  # Transform from grasp pose frame to pre-grasp pose frame (xyzrpy)
  pre_grasp_transform: [0.0, 0.0, -0.1, 0.0, 0.0, 0.0]

  #------------------------ Vacuuming action -----------------------#
  # Transform from object frame to grasp pose frame (xyzrpy) (DEFAULT)
  grasp_transform_vacuum: [0.662, -0.119, 0.274, 1.574, 0.206, 0.257]
  # Transform from grasp pose frame to pre-grasp pose frame (xyzrpy)
  pre_grasp_transform_vacuum: [0.0, 0.10, 0, 0.0, 0.0, 0.0]
  


  #------------------------- Prethrowing action ----------------------#

  # Transform from object frame to grasp pose frame (xyzrpy) (DEFAULT)
  grasp_transform_prethrown: [0.635, 0.049, 0.497, 1.622, -0.029, 0.136]
  # Transform from grasp pose frame to pre-grasp pose frame (xyzrpy)
  pre_grasp_transform_prethrown: [0.0, 0.0, 0, 0.0, 0.0, 0.0]

    #------------------------- Throwing action ----------------------#

  # Transform from object frame to grasp pose frame (xyzrpy) (DEFAULT)
  grasp_transform_thrown: [0.635, 0.049, 0.497, -1.625, 0.656, -0.048]
  # Transform from grasp pose frame to pre-grasp pose frame (xyzrpy)
  pre_grasp_transform_thrown: [0.0, 0.0, 0, 0.0, 0.0, 0.0]


  #------------------------ Throwing action -----------------------#
  throwing_joints: [0.03641659982267179, -0.15202623706946536, -0.35605605411905084, -1.990452139775332, 1.4154223989535004, 1.3276150379294405, 0.42337106602313235]

  ######################################################################


  # The joint configuration for place
  place_joints: [0.13173753611513103, 0.6463656097044025, 0.3532548962979362, -1.836787588992318, -1.4020667830440734, 1.2804275251831323, 0.7702129185133509]
  # The joint configuration for handover
  handover_joints: [-0.101, 0.161, 0.159, -1.651, 2.023, 2.419, -0.006]
  # The threshold on tau_ext for handover hand opening
  handover_thresh: 1.0

  # The personalized grasp pose maps for different objects
  poses_map:
    "object1" : [0.762, -0.272, 0.193, -3.111, -0.055, -0.048]
    "object2" : [0.783, 0.184, 0.195, -2.986, -0.025, -0.016]
    # "object3" : [0.478, -0.607, 0.511, 1.567, 0.106, 0.129]
    # "object4" : [0.478, -0.607, 0.511, 1.567, 0.106, 0.129]
    # "object5" : [0.478, -0.607, 0.511, 1.567, 0.106, 0.129]
    # "object6" : [0.478, -0.607, 0.511, 1.567, 0.106, 0.129]