# Parameters for task sequencer
# Remember that there might be other important constants that can only be changed from the src code.

task_sequencer:
  # Name of the robot
  robot_name: panda_arm
  # Name of the robot joints (without the number of the joints)
  robot_joints_name: panda_joint
  # Position controller
  pos_controller: position_joint_trajectory_controller
  # Impedance controller
  imp_controller: cartesian_impedance_controller_softbots_stiff_matrix
  # Name of the topic where the object pose is published
  object_topic_name: /irim_demo/chosen_object

  # The joint configuration for home
  home_joints: [-0.035, -0.109, -0.048, -1.888, 0.075, 1.797, -0.110] 

  # Transform from object frame to grasp pose frame (xyzrpy) (DEFAULT)
  # grasp_transform: [-0.04, -0.04, 0.145, -3.1415, 0.0, 0.0] (default)
  grasp_transform: [0.478, -0.607, 0.511, 1.567, 0.106, 0.129]
  # Transform from grasp pose frame to pre-grasp pose frame (xyzrpy)
  pre_grasp_transform: [0.0, 0.0, -0.1, 0.0, 0.0, 0.0]

  # Transform from object frame to grasp pose frame (xyzrpy) (DEFAULT)
  grasp_transform_vacuum: [0.612, -0.335, 0.395, 2.397, -0.458, 0.010]
  # Transform from grasp pose frame to pre-grasp pose frame (xyzrpy)
  pre_grasp_transform_vacuum: [0.0, 0.0, -0.10, 0.0, 0.0, 0.0]


  # The joint configuration for place
  place_joints: [0.13173753611513103, 0.6463656097044025, 0.3532548962979362, -1.836787588992318, -1.4020667830440734, 1.2804275251831323, 0.7702129185133509]
  # The joint configuration for handover
  handover_joints: [-0.101, 0.161, 0.159, -1.651, 2.023, 2.419, -0.006]
  # The threshold on tau_ext for handover hand opening
  handover_thresh: 1.0

  # The personalized grasp pose maps for different objects
  poses_map:
    "object1" : [0.762, -0.272, 0.193, -3.111, -0.055, -0.048]
    "object2" : [0.783, 0.184, 0.195, -2.986, -0.025, -0.016]
    # "object3" : [0.478, -0.607, 0.511, 1.567, 0.106, 0.129]
    # "object4" : [0.478, -0.607, 0.511, 1.567, 0.106, 0.129]
    # "object5" : [0.478, -0.607, 0.511, 1.567, 0.106, 0.129]
    # "object6" : [0.478, -0.607, 0.511, 1.567, 0.106, 0.129]